<a href="https://colab.research.google.com/github/jaehun5708/aipython/blob/main/240109.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [3]:
import numpy as np
# 1차원 배열
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
# 2차원 배열
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
# 배열의 형태, 차원, 데이터 타입 확인
print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)
print("Data Type:", arr2d.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Data Type: int64


In [4]:
import numpy as np
# 0부터 9까지
arr = np.arange(10)
print(arr)
# 2부터 19까지, 간격은 2
arr = np.arange(2, 20, 2)
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [5]:
import numpy as np
# 1차원 배열
zeros_1d = np.zeros(5)
print(zeros_1d)
# 2차원 배열
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
import numpy as np
# 1차원 배열
ones_1d = np.ones(5)
print(ones_1d)
# 2차원 배열
ones_2d = np.ones((3, 4))
print(ones_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
import numpy as np
# 1차원 배열
arr_1d = np.random.rand(5)
print(arr_1d)
# 2차원 배열
arr_2d = np.random.rand(2, 3)
print(arr_2d)

[0.528621   0.17220757 0.47115862 0.38061066 0.78594888]
[[0.02610507 0.70588906 0.00325031]
 [0.85017641 0.4977351  0.71091555]]


In [12]:
# 0부터 1까지 5개의 값
arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [14]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("합:",np.sum(arr))
print("행의 원소 합: ",np.sum(arr, axis=0))
print("열의 원소 합: ",np.sum(arr, axis=1))
print("평균:",np.mean(arr))
print("행의 원소 평균: ",np.mean(arr, axis=0))
print("열의 원소 평균: ",np.mean(arr, axis=1))
print("최대:",np.max(arr))
print("최소:",np.min(arr))
print("행의 원소 최대값: ",np.max(arr, axis=0))
print("행의 원소 최소값: ",np.min(arr, axis=0))
print("열의 원소 최대값: ",np.max(arr, axis=1))
print("열의 원소 최소값: ",np.min(arr, axis=1))
print(np.argmax(arr))
print(np.argmin(arr))
print("분산:",np.var(arr))
print("표준편차:",np.std(arr))

합: 21
행의 원소 합:  [5 7 9]
열의 원소 합:  [ 6 15]
평균: 3.5
행의 원소 평균:  [2.5 3.5 4.5]
열의 원소 평균:  [2. 5.]
최대: 6
최소: 1
행의 원소 최대값:  [4 5 6]
행의 원소 최소값:  [1 2 3]
열의 원소 최대값:  [3 6]
열의 원소 최소값:  [1 4]
5
0
분산: 2.9166666666666665
표준편차: 1.707825127659933


In [18]:
import numpy as np
arr = np.arange(1,10,2)
print(arr)

ones_2d = np.ones((3, 4))
print(ones_2d)

arr = np.linspace(0, 1, 10)
print(arr)

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [19]:
import numpy as np
arr1 = np.ones([3,4])
print(arr1)
print('size :', arr1.size)
print('dtype :', arr1.dtype)
print('shape :', arr1.shape)
print('ndim :',arr1.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2


In [20]:
import numpy as np
arr1 = np.array([[1,2,3],
[4,5,6],
[7,8,9]])
print(arr1[0])
print(arr1[0,2])
print(arr1[1:])
print(arr1[arr1 > 5])

[1 2 3]
3
[[4 5 6]
 [7 8 9]]
[6 7 8 9]


In [41]:
a = np.arange(1, 26).reshape(5,5)
print(a)
print(a.shape)
print(a[3,3])
print(a[0:2,0:2])
print(a[3:5,3:5])
print(a[0:2,0:5])
print(a[0:5,3:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [43]:
arr=np.array([[1,2,3],[4,5,6]])
arr_T=arr.transpose()
arr_F=arr.flatten()
arr_R=arr_F.reshape(3,2)
print(arr)
print(arr_T)
print(arr_F)
print(arr_R)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [51]:
import numpy as np
a = np.arange(1, 37).reshape(3,3,4)
print(a)
print(a.shape)
print(a.size)
print(a.reshape(3,4,3))
print(a.flatten())

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
